---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ../../../../templates/volsync
configMapGenerator:
  - name: minecraft-lobby-configmap
    files:
      - luckperms.yml=./config/luckperms.yml
      - paper-global.yml=./config/paper-global.yml
generatorOptions:
  disableNameSuffixHash: true
#   annotations:
#     kustomize.toolkit.fluxcd.io/substitute: disabled
