---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: idrac-fan-controller
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: idrac-fan-controller-secret
    template:
      data:
        IDRAC_USERNAME: "{{ .IDRAC_USERNAME }}"
        IDRAC_PASSWORD: "{{ .IDRAC_PASSWORD }}"
  dataFrom:
    - extract:
        key: idrac
