---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age16la8m5zvpastlq7jzmv5agmfkghq4ckw28jy8lacqqyxmw2c8y3s9cpunf"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age16la8m5zvpastlq7jzmv5agmfkghq4ckw28jy8lacqqyxmw2c8y3s9cpunf"
stores:
  yaml:
    indent: 2
