---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app minio
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      minio:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: quay.io/minio/minio
              tag: RELEASE.2025-04-22T22-12-26Z
            env:
              TZ: "${TIMEZONE}"
              MINIO_UPDATE: "off"
              MINIO_PROMETHEUS_URL: http://kube-prometheus-stack-prometheus.observability:9090
              MINIO_PROMETHEUS_JOB_ID: minio
              MINIO_PROMETHEUS_AUTH_TYPE: public
              MINIO_BROWSER_REDIRECT_URL: https://minio.westphal.io
              # This breaks all login attempts to the webpage
              # MINIO_SERVER_URL: https://s3.westphal.io
              MINIO_API_CORS_ALLOW_ORIGIN: https://minio.westphal.io,https://s3.westphal.io
            envFrom:
              - secretRef:
                  name: minio-secret
            args: ["server", "/data", "--console-address", ":9001"]
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /minio/health/live
                    port: &api-port 9000
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  timeoutSeconds: 10
                  failureThreshold: 6
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                memory: 100Mi
                cpu: 100m
              limits:
                memory: 2000Mi
        # pod:
        #   securityContext:
        #     runAsUser: 3000
        #     runAsGroup: 3000
        #     fsGroup: 3000
        #     fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: *app
        ports:
          http:
            port: 9001
          s3:
            port: *api-port
    serviceMonitor:
      app:
        serviceName: *app
        endpoints:
          - port: s3
            scheme: http
            path: /minio/v2/metrics/cluster
            interval: 1m
            scrapeTimeout: 10s
    ingress:
      app:
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Storage
          gethomepage.dev/name: Minio
          gethomepage.dev/icon: minio.svg
          gethomepage.dev/description: S3 Object Storage
        hosts:
          - host: &host "{{ .Release.Name }}.westphal.io"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
          - host: &s3host s3.westphal.io
            paths:
              - path: /
                service:
                  identifier: app
                  port: s3
        tls:
          - hosts:
              - *host
              - *s3host
    persistence:
      config:
        existingClaim: minio-nfs
        globalMounts:
          - path: /data
