---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: &name minio-nfs
spec:
  storageClassName: *name
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${SECRET_NFS_SERVER}
    path: /mnt/sega/k8s
  mountOptions:
    - nfsvers=4
    - nconnect=8
    - hard
    - noatime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: &name minio-nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: *name
  resources:
    requests:
      storage: 1Mi
