---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tautulli
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      tautulli:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/joryirving/tautulli
              tag: 2.15.3@sha256:99bb6251f51ed985abe1587dd92b9529488889577ea66d5a153e47b1d0bc5e39
            env:
              TZ: ${TIMEZONE}
              TAUTULLI_HTTP_BASE_URL: https://tautulli.${SECRET_DOMAIN}
              TAUTULLI__PORT: &port 80
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /status
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        enabled: true
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: tautulli.png
          gethomepage.dev/name: Tautulli
          gethomepage.dev/group: Media
          gethomepage.dev/weight: "50"
          gethomepage.dev/widget.type: tautulli
          gethomepage.dev/widget.url: http://tautulli.media:80
          gethomepage.dev/widget.key: "{{ `{{HOMEPAGE_VAR_TAUTULLI_KEY}}` }}"
          gethomepage.dev/widget.enableUser: "true"
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
      config-cache:
        existingClaim: "{{ .Release.Name }}-cache"
        globalMounts:
          - path: /config/cache
      tmpfs:
        type: emptyDir
        advancedMounts:
          tautulli:
            app:
              - path: /config/logs
                subPath: logs
              - path: /tmp
                subPath: tmp
