---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: nextcloud-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        nextcloud-username: "{{ .NEXTCLOUD_ADMIN_USER }}"
        nextcloud-password: "{{ .NEXTCLOUD_ADMIN_PASS }}"
        OIDC_CLIENT_ID: "{{ .NEXTCLOUD_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .NEXTCLOUD_CLIENT_SECRET }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: nextcloud
        INIT_POSTGRES_HOST: postgres17-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: nextcloud
    - extract:
        key: cloudnative-pg