---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wizarr-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: wizarr
        group: external
        url: https://join.${SECRET_DOMAIN}/api/status?WIZARR_API_KEY=${WIZARR_API_KEY}
        interval: 1m
        conditions:
          - "[CONNECTED] == true"
        alerts:
          - type: pushover