---
apiVersion: v1
kind: Service
metadata:
  name: proxmox
  namespace: network
spec:
  type: ClusterIP
  ports:
    - port: 443
      protocol: TCP
      targetPort: 8006
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: &app proxmox
  namespace: network
  labels:
    kubernetes.io/service-name: *app
addressType: IPv4
ports:
  - name: http
    appProtocol: http
    protocol: TCP
    port: 8006
endpoints:
  - addresses:
      - "${SECRET_HOST_IP}"
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: &app proxmox
spec:
  hostnames: ["proxmox.${SECRET_DOMAIN}"]
  parentRefs:
    - name: internal
      namespace: kube-system
      sectionName: https
  rules:
    - backendRefs:
        - name: *app
          namespace: network
          port: 443
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/icon: proxmox.png
    gethomepage.dev/name: Proxmox
    gethomepage.dev/group: Infrastructure
    gethomepage.dev/description: Cluster Hypervisor
    gethomepage.dev/widget.type: proxmox
    gethomepage.dev/widget.url: https://${SECRET_HOST_IP}:8006
    gethomepage.dev/widget.username: '{{HOMEPAGE_VAR_PROXMOX_USER}}'
    gethomepage.dev/widget.password: '{{HOMEPAGE_VAR_PROXMOX_PASS}}'
