---
apiVersion: v1
kind: Service
metadata:
  name: nas
  namespace: network
spec:
  type: ClusterIP
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443

---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: &app nas
  namespace: network
  labels:
    kubernetes.io/service-name: *app
addressType: IPv4
ports:
  - name: http
    appProtocol: http
    protocol: TCP
    port: 443
endpoints:
  - addresses:
      - "${SECRET_NFS_SERVER}"
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: &app nas
spec:
  hostnames: ["nas.${SECRET_DOMAIN}"]
  parentRefs:
    - name: internal
      namespace: kube-system
      sectionName: https
  rules:
    - backendRefs:
        - name: nas
          namespace: network
          port: 443
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/icon: truenas-scale.png
    gethomepage.dev/name: TrueNAS
    gethomepage.dev/group: Infrastructure
    gethomepage.dev/description: Primary Network Attached Storage
    gethomepage.dev/widget.type: truenas
    gethomepage.dev/widget.url: https://${SECRET_NFS_SERVER}
    gethomepage.dev/widget.key: '{{HOMEPAGE_VAR_TRUENAS_KEY}}'
    gethomepage.dev/widget.enablePools: true
