---
apiVersion: v1
kind: Service
metadata:
  name: unifi-ui
  namespace: network
spec:
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: unifi-ui
  namespace: network
  labels:
    kubernetes.io/service-name: unifi-ui
addressType: IPv4
ports:
  - name: http
    appProtocol: http
    protocol: TCP
    port: 443
endpoints:
  - addresses:
      - "${SECRET_UNIFI_IP}"
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: &app unifi-ui
spec:
  hostnames: ["unifi.${SECRET_DOMAIN}"]
  parentRefs:
    - name: internal
      namespace: kube-system
      sectionName: https
  rules:
    - backendRefs:
        - name: *app
          namespace: network
          port: 443
  # annotations:
  #   gethomepage.dev/enabled: "true"
  #   gethomepage.dev/name: Unifi
  #   gethomepage.dev/group: Network
  #   gethomepage.dev/icon: unifi.png
  #   gethomepage.dev/description: Home Network Portal
  #   gethomepage.dev/widget.type: unifi
  #   gethomepage.dev/widget.url: https://${SECRET_UNIFI_IP}:443
  #   gethomepage.dev/widget.username: '{{HOMEPAGE_VAR_UNIFI_USER}}'
  #   gethomepage.dev/widget.password: '{{HOMEPAGE_VAR_UNIFI_PASS}}'
