---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: authentik-secret
    template:
      data:
        # Authentik DBs
        AUTHENTIK_POSTGRESQL__HOST: &dbhost postgres16-rw.database.svc.cluster.local
        AUTHENTIK_POSTGRESQL__NAME: &dbname authentik
        AUTHENTIK_POSTGRESQL__USER: &dbuser "{{ .AUTHENTIK_POSTGRES_USER }}"
        AUTHENTIK_POSTGRESQL__PASSWORD: &dbpass "{{ .AUTHENTIK_POSTGRES_PASS }}"
        AUTHENTIK_REDIS__DB: "1"
        AUTHENTIK_SECRET_KEY: "{{ .AUTHENTIK_SECRET_KEY }}"

        # Authentik SMTP
        AUTHENTIK_EMAIL__HOST: "{{ .SMTP_HOST }}"
        AUTHENTIK_EMAIL__PORT: "{{ .SMTP_PORT }}"
        AUTHENTIK_EMAIL__USERNAME: "{{ .SMTP_EMAIL }}"
        AUTHENTIK_EMAIL__PASSWORD: "{{ .SMTP_PASSWORD }}"
        # AUTHENTIK_EMAIL__USE_SSL: "true"
        AUTHENTIK_EMAIL__USE_TLS: "true"
        AUTHENTIK_EMAIL__FROM: "{{ .SMTP_SENDER }}"

        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: authentik
    - extract:
        key: cloudnative-pg
    - extract:
        key: smtp
