apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: immich-client-ip-affinity
  namespace: media
spec:
  targetRef:
    group: "gateway.networking.k8s.io"
    kind: HTTPRoute
    name: immich
  loadBalancer:
    type: ConsistentHash
    consistentHash:
      type: SourceIP