---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-configmap
  namespace: media
data:
  DB_PORT: "5432"
  IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning.media.svc.cluster.local:3003
  IMMICH_SERVER_URL: http://immich-server.media.svc.cluster.local:3001
  LOG_LEVEL: verbose
  NODE_ENV: "production"
  REDIS_HOSTNAME: dragonfly.databases.svc.cluster.local
  REDIS_PORT: "6379"
  REDIS_DBINDEX: "3"
  IMMICH_PORT: "3001"
  TZ: "${TIMEZONE}"
