---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name immich-config-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      templateFrom:
        - configMap:
            name: immich-config-tpl
            items:
              - key: immich-config.yaml
  dataFrom:
    - extract:
        key: immich
    - extract:
        key: smtp
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: immich-secret
    template:
      data:
        username: "{{ .POSTGRES_SUPER_USER }}"
        password: "{{ .POSTGRES_SUPER_PASS }}"
        # Switch to this when creating new version
        # aws-access-key-id: "{{ .MINIO_ROOT_USER }}"
        # aws-secret-access-key: "{{ .MINIO_ROOT_PASSWORD }}"
        aws-access-key-id: "{{ .AWS_ACCESS_KEY_ID }}"
        aws-secret-access-key: "{{ .AWS_SECRET_ACCESS_KEY }}"
        # Immich
        DB_DATABASE_NAME: &dbname immich
        DB_HOSTNAME: &dbhost immich17-rw.media.svc.cluster.local
        DB_USERNAME: &dbuser "{{ .IMMICH_POSTGRES_USER }}"
        DB_PASSWORD: &dbpass "{{ .IMMICH_POSTGRES_PASS }}"
        JWT_SECRET: "{{ .IMMICH_JWT_SECRET }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        INIT_POSTGRES_USER_FLAGS: "-s"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: immich
    - extract:
        key: cloudnative-pg
    - extract:
        key: minio-secret
