---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vpn-gateway
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: vpn-gateway-secret
    template:
      engineVersion: v2
      data:
        ## OPENVPN_USER: "{{ .PIA_USERNAME }}"
        ## OPENVPN_PASSWORD: "{{ .PIA_PASSWORD }}"
        WIREGUARD_ENDPOINT_IP: "{{ .WIREGUARD_ENDPOINT_IP }}"
        WIREGUARD_ENDPOINT_PORT: "{{ .WIREGUARD_ENDPOINT_PORT }}"
        WIREGUARD_PUBLIC_KEY: "{{ .WIREGUARD_PUBLIC_KEY }}"
        WIREGUARD_PRIVATE_KEY: "{{ .WIREGUARD_PRIVATE_KEY }}"
        WIREGUARD_ADDRESSES: "{{ .WIREGUARD_ADDRESSES }}"
  dataFrom:
  - extract:
      key: vpn-gateway
