---
role_assignment:
    driver: oidc
    oidc_role_mapper:
        role_claim: groups
        role_mapping:
            - role_name: admin
              claim_value: ocisAdmin
            - role_name: spaceadmin
              claim_value: ocisSpaceAdmin
            - role_name: user
              claim_value: ocisUser
            - role_name: guest
              claim_value: ocisGuest
