---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: minecraft-create-configmap
    files:
      - luckperms.conf=./config/luckperms.conf
      - pcf-common.toml=./config/pcf-common.toml
      - create.toml=./config/create.toml
generatorOptions:
  disableNameSuffixHash: true
