---
# See vanilla/route-services.yaml for what these do.
apiVersion: v1
kind: Service
metadata:
  name: create
spec:
  type: ExternalName
  externalName: minecraft-router.games.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: create-creative
spec:
  type: ExternalName
  externalName: minecraft-router.games.svc.cluster.local
