---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app minecraft-velocity
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      strategy: rollback
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    controllers:
      velocity:
        replicas: 1
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 17.6
            envFrom: &envFrom
              - secretRef:
                  name: minecraft-velocity-secret
        containers:
          app:
            nameOverride: *app
            image:
              repository: itzg/mc-proxy
              tag: java21@sha256:f79c958dfc4ba71b96a3e959941280ad7136e0eae86fde443e7b7bde729b22f7
            tty: true
            env:
              TZ: ${TIMEZONE}
              UID: "1000"
              GID: "1000"
              TYPE: VELOCITY
              # TODO renovate
              MINECRAFT_VERSION: 1.21.8
              VELOCITY_VERSION: "3.4.0-SNAPSHOT"
              VELOCITY_BUILD_ID: 528
              OVERRIDE_ICON: "true"
              # PLUGINS_FILE: /config/plugins.txt
              INIT_MEMORY: 128M
              MAX_MEMORY: 256M
              # https://docs.papermc.io/velocity/getting-started#launching-velocity-under-macos-or-linux
              JVM_XX_OPTS: "-XX:+UseG1GC -XX:G1HeapRegionSize=4M -XX:+UnlockExperimentalVMOptions -XX:+ParallelRefProcEnabled -XX:+AlwaysPreTouch -XX:MaxInlineLevel=15"
              ENABLE_RCON: "false"
              REPLACE_ENV_VARIABLES: "TRUE"
              REMOVE_OLD_MODS: "true"
              MODRINTH_DEFAULT_VERSION_TYPE: release
              MODRINTH_PROJECTS: |-
                mckotlin:3PY3lTnr
                minimotd
                miniplaceholders
                papiproxybridge:jR1s02Y5
                simple-voice-chat:NeIJv4rE
                velocitab:OLhjLWrJ
                viabackwards
                viaversion
                vlobby:p5lOYrvy
                vpacketevents:Kz7ttviZ
              PLUGINS: |-
                https://github.com/FeuSalamander/Vmessage/releases/download/1.6.2/Vmessage.jar
                https://download.luckperms.net/1596/velocity/LuckPerms-Velocity-5.5.11.jar
            envFrom: *envFrom
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true
            probes:
              readiness: &probes
                enabled: true
                type: TCP
                port: 25565
              liveness: *probes
              startup:
                <<: *probes
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 250m
                memory: 250Mi
              # limits:
              #   cpu: 500m
              #   memory: 1Gi

    service:
      velocity:
        controller: velocity
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 10.10.40.150
        ports:
          velocity-proxy:
            port: 25565
            protocol: TCP
            # targetPort: velocity
          voice-proxy:
            port: 25577
            protocol: UDP
            # targetPort: voice
          bedrock-proxy:
            port: 19132
            protocol: UDP
            # targetPort: bedrock
      rcon:
        controller: velocity
        ports:
          rcon:
            port: 25575
            protocol: TCP
            # targetPort: rcon
      metrics:
        controller: velocity
        ports:
          metrics:
            port: 9100
            protocol: TCP
            # targetPort: metrics

    serviceMonitor:
      metrics:
        # TODO: This was using the wrong ip in prometheus?
        enabled: false
        serviceName: minecraft-velocity-metrics
        endpoints:
          - port: metrics
            scheme: http
            path: /
            interval: 1m

    persistence:
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
      data:
        enabled: true
        existingClaim: *app
        globalMounts:
          - path: /server
      config:
        type: configMap
        name: minecraft-velocity-config
        globalMounts:
          - path: /config/velocity.toml
            subPath: velocity.toml
            readOnly: true
          - path: /config/plugins/luckperms/config.yml
            subPath: luckperms.yaml
            readOnly: true
          - path: /config/plugins/voicechat/voicechat-proxy.properties
            subPath: voice.conf
            readOnly: true
          - path: /config/plugins/velocitab/tab_groups.yml
            subPath: velocitab.yaml
            readOnly: true
          - path: /config/plugins/vmessage/config.toml
            subPath: vmessage.toml
            readOnly: true
          - path: /config/plugins/vlobby/configuration.conf
            subPath: vlobby.conf
            readOnly: true
          - path: /config/plugins/minimotd-velocity/extra-configs/create.conf
            subPath: config-create.conf
            readOnly: true
          - path: /config/plugins/minimotd-velocity/extra-configs/vanilla.conf
            subPath: config-vanilla.conf
            readOnly: true
          - path: /config/plugins/minimotd-velocityextra-configs/creative.conf
            subPath: config-creative.conf
            readOnly: true
          - path: /config/plugins/minimotd-velocity/main.conf
            subPath: minimotd.conf
            readOnly: true
          - path: /config/plugins/minimotd-velocity/plugin_settings.conf
            subPath: minimotd-settings.conf
            readOnly: true
      forwarding-secret:
        type: secret
        name: minecraft-velocity-secret
        items:
          - key: VELOCITY_FORWARDING_SECRET
            path: forwarding.secret
        globalMounts:
          - path: /config/forwarding.secret
            subPath: forwarding.secret
            readOnly: true
