---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ./dnsendpoint.yaml
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ../../../../templates/volsync
configMapGenerator:
  - name: minecraft-velocity-config
    files:
      - velocity.toml=config/velocity.toml
      - luckperms.yaml=config/luckperms.yaml
      - voice.conf=config/voice.conf
      - vlobby.conf=config/vlobby.conf
      - vmessage.toml=config/vmessage.toml
      - velocitab.yaml=config/velocitab.yaml
      - config-create.conf=config/minimotd/extra-configs/create.conf
      - config-vanilla.conf=config/minimotd/extra-configs/vanilla.conf
      - config-creative.conf=config/minimotd/extra-configs/creative.conf
      - minimotd.conf=config/minimotd/main.conf
      - minimotd-settings.conf=config/minimotd/plugin_settings.conf
generatorOptions:
  disableNameSuffixHash: true
