---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: scrob
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: scrob-secret
    template:
      engineVersion: v2
      data:
        SECRET_KEY: "{{ .SCROB_SECRET_KEY }}"
        POSTGRES_HOST: &dbHost postgres17-rw.database.svc.cluster.local
        POSTGRES_PORT: "5432"
        POSTGRES_USER: &dbUser "{{ .SCROB_POSTGRES_USER }}"
        POSTGRES_PASSWORD: &dbPass "{{ .SCROB_POSTGRES_PASSWORD }}"
        POSTGRES_DB: &dbName scrob
        # PUSHOVER_TOKEN: "{{ .RADARR_PUSHOVER_TOKEN }}"
        # PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY }}"
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: scrob
