---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: scrob
spec:
  chartRef:
    kind: OCIRepository
    name: scrob
  interval: 15m
  dependsOn: []
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 0
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 0
        runAsNonRoot: false
        runAsUser: 0
    controllers:
      scrob:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18.6
            envFrom: &envFrom
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
        containers:
          app:
            image:
              repository: ghcr.io/ellite/scrob
              tag: 2.11.0@sha256:58a37fdf7e27d39de2f1ce3116b1d507cec2543b5aa3ba2cb5eff39d2ac5c9b1
            env:
              TZ: ${TIMEZONE}
              SERVER_URL: https://scrob.${SECRET_DOMAIN}
              OIDC_ENABLED: "true"
              OIDC_PROVIDER_NAME: Authentik
              OIDC_AUTH_URL: https://sso.${SECRET_DOMAIN}/application/o/authorize/
              OIDC_TOKEN_URL: https://sso.${SECRET_DOMAIN}/application/o/token/
              OIDC_USERINFO_URL: https://sso.${SECRET_DOMAIN}/application/o/userinfo/
              OIDC_LOGOUT_URL: https://sso.${SECRET_DOMAIN}/application/o/scrob/end-session/
              OIDC_REDIRECT_URL: https://scrob.${SECRET_DOMAIN}/oidc-callback
              OIDC_SCOPES: openid email profile
              OIDC_IDENTIFIER_FIELD: email
              OIDC_AUTO_CREATE_USERS: "true"
              OIDC_DISABLE_PASSWORD_LOGIN: "false"
            envFrom: *envFrom
            resources:
              requests:
                cpu: 10m
                memory: 150Mi
              limits:
                memory: 1Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /app/backend/data
      tmpfs:
        type: emptyDir
        advancedMounts:
          scrob:
            app:
              - path: /tmp
                subPath: tmp
    route:
      app:
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Plex Tools
          gethomepage.dev/name: Scrob
          gethomepage.dev/icon: mdi-music-note
          gethomepage.dev/description: Plex scrobble dashboard
    service:
      app:
        ports:
          http:
            port: 7330
