---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_GAMING_DOMAIN/./-}"
spec:
  secretName: "${SECRET_GAMING_DOMAIN/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${SECRET_GAMING_DOMAIN}"
  dnsNames: ["${SECRET_GAMING_DOMAIN}", "*.${SECRET_GAMING_DOMAIN}"]
