# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app minecraft-vanilla
spec:
  interval: 15m
  timeout: 5m
  maxHistory: 3
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    controllers:
      minecraft-vanilla:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/itzg/minecraft-server
              tag: java21@sha256:46d0f2df9406a3f1df7d6e3a98235ff7459ba06e512676b3e53c62a4457b5a7f
            tty: true
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  periodSeconds: 60
                  exec: &mc-health { command: ["mc-health"] }
              readiness: *probes
              startup:
                <<: *probes
                spec:
                  initialDelaySeconds: 60
                  periodSeconds: 1
                  failureThreshold: 300
                  exec: *mc-health
            env:
              # Server Configuration
              ## General
              EULA: "true"
              TZ: "${TIMEZONE}"
              TYPE: FABRIC
              # ENABLE_AUTOPAUSE: TRUE
              MAX_TICK_TIME: "-1"
              # renovate: depName=minecraft datasource=custom.minecraft versioning=semver-coerced
              VERSION: 1.20.4
              OVERRIDE_SERVER_PROPERTIES: "true"
              MOTD: "Our long term persistent vanilla server"
              DIFFICULTY: hard
              SEED: "722314537282636262"
              LEVEL: "vanilla"
              MODE: "survival"
              SPAWN_PROTECTION: 0
              FORCE_REDOWNLOAD: "true"
              ONLINE_MODE: "false"
              ALLOW_FLIGHT: "true"
              REPLACE_ENV_IN_PLACE: "true"
              # Logging
              ENABLE_ROLLING_LOGS: "true"
              LOG_TIMESTAMP: "true"
              # Performance
              JVM_XX_OPTS: -XX:MaxRAMPercentage=75
              MAX_MEMORY: 6144M
              USE_AIKAR_FLAGS: "true"
              SNOOPER_ENABLED: "false"
              VIEW_DISTANCE: 14
              ## Mods
              REMOVE_OLD_MODS: "true"
              MODRINTH_DEFAULT_VERSION_TYPE: release
              MODRINTH_PROJECTS: |-
                crossstitch
                fabric-api
                luckperms
                worldedit
                krypton
                ferrite-core
                fabricproxy-lite
                lithium
                carpet
                simple-voice-chat
                starlight
                modernfix
                vanilla-permissions
              # VANILLATWEAKS_SHARECODE: 4miIMt # Coord HUD, Anti-Endermen Griefing for 1.20
              ENABLE_QUERY: "true"
              EXISTING_OPS_FILE: SYNCHRONIZE
            envFrom:
              - secretRef:
                  name: minecraft-vanilla-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop: [ALL]
                add: ["NET_RAW"]
            resources:
              requests:
                cpu: 300m
                memory: 3Gi
              limits:
                memory: 6Gi
    service:
      minecraft:
        controller: *app
        type: ClusterIP
        ports:
          java:
            port: 25565
            protocol: TCP
          voice:
            port: 24454
            protocol: UDP
          bedrock:
            port: 19132
            protocol: UDP
          # map:
          #   port: 8100
          rcon:
            port: 25575
          metrics:
            port: 25585
    serviceMonitor:
      metrics:
        enabled: false
        serviceName: *app
        endpoints:
          - port: metrics
            scheme: http
            path: /
            interval: 1m
    persistence:
      data:
        existingClaim: *app
      config:
        enabled: true
        type: configMap
        name: minecraft-vanilla-configmap
        globalMounts:
          - subPath: luckperms.conf
            path: /config/luckperms/luckperms.conf
          - subPath: fabricproxy.toml
            path: /config/FabricProxy-Lite.toml
