---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: minecraft-vanilla-configmap
    files:
      - luckperms.conf=./config/luckperms.conf
      - fabricproxy.toml=./config/fabricproxy.toml
generatorOptions:
  disableNameSuffixHash: true
