---
originRequest:
  originServerName: "external.westphal.io"

ingress:
  - hostname: "westphal.io"
    service: &svc https://cilium-gateway-external.kube-system.svc.cluster.local
  - hostname: "*.westphal.io"
    service: *svc
  - service: http_status:404
