---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app icarus
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    replace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      strategy: rollback
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  values:
    controllers:
      icarus:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            nameOverride: *app
            image:
              repository: mornedhels/icarus-server
              tag: 1.0.0
              pullPolicy: IfNotPresent
            env:
                SERVER_PORT: &port 17777
                SERVER_QUERYPORT: &queryport 27015
                PUID: "4711"
                PGID: "4711"
                TZ: ${TIMEZONE}
            envFrom:
              - secretRef:
                  name: icarus-secret
            resources:
              requests:
                memory: 8Gi
                cpu: 2000m
              limits:
                memory: 16Gi

    service:
      icarus:
        controller: *app
        type: LoadBalancer
        loadBalancerIP: 10.10.40.143
        ports:
          steam1:
            port: *port
            protocol: UDP
          steam2:
            port: *queryport
            protocol: UDP
    persistence:
      saves:
        existingClaim: *app
        advancedMounts:
          icarus:
            app:
              - path: /home/icarus/drive_c/icarus
                subPath: data
              - path: /opt/icarus
                subPath: game
