# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app sdtd
spec:
  interval: 15m
  timeout: 5m
  maxHistory: 3
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      sdtd:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            nameOverride: *app
            image:
              repository: vinanrra/7dtd-server
              tag: latest
              pullPolicy: IfNotPresent
            tty: true
            env:
              CHANGE_CONFIG_DIR_OWNERSHIP: YES
              LINUXGSM_VERSION: v24.3.4
              START_MODE: 0
              VERSION: stable
              PUID: 1000
              PGID: 1000
              TimeZone: ${TIMEZONE}
              TEST_ALERT: NO
              UPDATE_MODS: NO
              MODS_URLS: ""
              ALLOC_FIXES: NO
              ALLOC_FIXES_UPDATE: NO
              UNDEAD_LEGACY: NO
              UNDEAD_LEGACY_VERSION: stable
              UNDEAD_LEGACY_UPDATE: NO
              DARKNESS_FALLS: NO
              DARKNESS_FALLS_UPDATE: NO
              DARKNESS_FALLS_URL: False
              CPM: NO
              CPM_UPDATE: NO
              BEPINEX: NO
              BEPINEX_UPDATE: NO
              BACKUP: NO
              BACKUP_HOUR: 5
              BACKUP_MAX: 7
              MONITOR: NO
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              # capabilities:
              #   drop: [ALL]
            resources:
              requests:
                cpu: 500m
                memory: 2Gi
              limits:
                memory: 4Gi
    defaultPodOptions:
      automountServiceAccountToken: false
      securityContext:
        # runAsNonRoot: true
        # runAsUser: 1000
        # runAsGroup: 1000
        fsGroup: 1000
        # supplementalGroups: [1000]
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      7dtd:
        controller: *app
        type: LoadBalancer
        loadBalancerIP: 10.10.40.141
        ports:
          game-tcp:
            port: 26900
            protocol: TCP
          game-udp:
            port: 26900
            protocol: UDP
          steam-query1:
            port: 26901
            protocol: UDP
          steam-query2:
            port: 26902
            protocol: UDP
          webadmin:
            port: 8080
            protocol: TCP
          telnet:
            port: 8081
            protocol: TCP
          webserver:
            port: 8082
            protocol: TCP
    persistence:
      saves:
        existingClaim: *app
        advancedMounts:
          sdtd:
            app:
              - path: /home/sdtdserver/.local/share/7DaysToDie
      config:
        existingClaim: sdtd-config
        advancedMounts:
          sdtd:
            app:
              - path: /home/sdtdserver/lgsm/config-lgsm/sdtdserver
      serverfiles:
        existingClaim: sdtd-serverfiles
        advancedMounts:
          sdtd:
            app:
              - path: /home/sdtdserver/serverfiles
      log:
        type: emptyDir
        advancedMounts:
          sdtd:
            app:
              - path: /home/sdtdserver/log
      backup:
        type: emptyDir
        advancedMounts:
          sdtd:
            app:
              - path: /home/sdtdserver/lgsm/backup