---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: cnpg-grafana-dashboard
    files:
      - ./resources/cnp.json
    options:
      annotations:
        grafana_folder: "Data"
        kustomize.toolkit.fluxcd.io/substitute: disabled
      labels:
        grafana_dashboard: "1"
