---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: homepage-secret
    template:
      engineVersion: v2
      data:
        ## Non Cluster resources
        HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: "{{ .CLOUDFLARE_ACCOUNT_ID }}"
        HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: "{{ .CLOUDFLARE_TUNNEL_ID }}"
        HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: "{{ .CLOUDFLARE_API_KEY }}"
        # HOMEPAGE_VAR_PORTAINER_TOKEN: "{{ .PORTAINER_TOKEN }}"
        # HOMEPAGE_VAR_UNIFI_USER: "{{ .HOMEPAGE_UNIFI_USER }}"
        # HOMEPAGE_VAR_UNIFI_PASS: "{{ .HOMEPAGE_UNIFI_PASS }}"
        HOMEPAGE_VAR_UNIFI_KEY: "{{ .UNIFI_API_KEY }}"
        ## Infra
        HOMEPAGE_VAR_PROXMOX_USER: "{{ .PROXMOX_API_USER }}"
        HOMEPAGE_VAR_PROXMOX_PASS: "{{ .PROXMOX_API_PASS }}"
        HOMEPAGE_VAR_TRUENAS_KEY: "{{ .TRUENAS_API_KEY }}"
        HOMEPAGE_VAR_TRUENAS_BACKUP_KEY: "{{ .TRUENAS_BACKUP_API_KEY }}"
        # HOMEPAGE_VAR_PIHOLE_API_TOKEN: "{{ .PIHOLE_API_TOKEN }}"
        ## Default
        HOMEPAGE_VAR_HASS_LATITUDE: "{{ .HASS_LATITUDE }}"
        HOMEPAGE_VAR_HASS_LONGITUDE: "{{ .HASS_LONGITUDE }}"
        HOMEPAGE_VAR_HASS_TOKEN: "{{ .HASS_VSCODE_TOKEN }}"
        HOMEPAGE_VAR_PTERODACTYL_KEY: "{{ .PTERODACTYL_KEY }}"
        ## Downloads
        HOMEPAGE_VAR_PROWLARR_TOKEN: "{{ .PROWLARR_API_KEY }}"
        HOMEPAGE_VAR_RADARR_TOKEN: "{{ .RADARR_API_KEY }}"
        HOMEPAGE_VAR_SABNZBD_TOKEN: "{{ .SABNZBD_API_KEY }}"
        HOMEPAGE_VAR_SONARR_TOKEN: "{{ .SONARR_API_KEY }}"
        ## Media
        HOMEPAGE_VAR_OVERSEERR_TOKEN: "{{ .OVERSEERR_API_KEY }}"
        HOMEPAGE_VAR_PLEX_KEY: "{{ .PLEX_KEY }}"
        HOMEPAGE_VAR_TAUTULLI_KEY: "{{ .TAUTULLI_API_KEY }}"
        HOMEPAGE_VAR_WIZARR_TOKEN: "{{ .HOMEPAGE_WIZARR_TOKEN }}"
        HOMEPAGE_VAR_IMMICH_TOKEN: "{{ .IMMICH_API_KEY }}"
        ## Observability
        HOMEPAGE_VAR_GRAFANA_USERNAME: "{{ .GRAFANA_ADMIN_USER }}"
        HOMEPAGE_VAR_GRAFANA_PASSWORD: "{{ .GRAFANA_ADMIN_PASS }}"
        HOMEPAGE_VAR_GLANCES_USERNAME: "{{ .GLANCES_USER }}"
        HOMEPAGE_VAR_GLANCES_PASSWORD: "{{ .GLANCES_PASS }}"
        ## Security
        HOMEPAGE_VAR_AUTHENTIK_TOKEN: "{{ .HOMEPAGE_AUTHENTIK_TOKEN }}"
  dataFrom:
  - extract:
      key: authentik
  - extract:
      key: cloudflare
  - extract:
      key: immich
  - extract:
      key: glances
  - extract:
      key: grafana
  - extract:
      key: home-assistant
  - extract:
      key: overseerr
  - extract:
      key: pihole
  - extract:
      key: plex
  - extract:
      key: prowlarr
  - extract:
      key: proxmox
  - extract:
      key: pterodactyl
  - extract:
      key: radarr
  - extract:
      key: sabnzbd
  - extract:
      key: sonarr
  - extract:
      key: tautulli
  - extract:
      key: truenas
  - extract:
      key: unifi
  - extract:
      key: wizarr
