---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich17
spec:
  instances: 3
  # Vectorchord Image
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:17.5-0.3.0
  primaryUpdateStrategy: unsupervised
  storage:
    size: 20Gi
    storageClass: openebs-hostpath
  superuserSecret:
    name: immich-secret
  enableSuperuserAccess: true
  postgresql:
    parameters:
      auto_explain.log_min_duration: '10s'
      max_connections: "300"
      max_wal_size: 512MB
      shared_buffers: 2048MB
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
    shared_preload_libraries:
      - "vchord.so"
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true
  resources:
    requests:
      cpu: 500m
    limits:
      memory: 4Gi
  monitoring:
    enablePodMonitor: true
    podMonitorMetricRelabelings:
      - { sourceLabels: ["cluster"], targetLabel: cnpg_cluster, action: replace }
      - { regex: cluster, action: labeldrop }
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: immich-garage
        # Note: serverName version needs to be incremented
        # when recovering from an existing cnpg cluster
        serverName: immich17-v7
  # Note: previousCluster needs to be set to the name of the previous
  # cluster when recovering from an existing cnpg cluster
  bootstrap:
    # initdb:
    #   postInitSQL:
    #     - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
    recovery:
      source: immich17-v6
  # Note: externalClusters is needed when recovering from an existing cnpg cluster
  externalClusters:
    - name: immich17-v6
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: immich-garage
          serverName: immich17-v6
