---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cnpg-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: immich-db
        group: infrastructure
        url: tcp://immich17-lb.media.svc.cluster.local:5432
        interval: 1m
        conditions: ["[CONNECTED] == true"]
        alerts:
          - type: pushover
        ui:
          hide-url: true
          hide-hostname: true
