---
apiVersion: v1
kind: Service
metadata:
  name: immich-lb
  annotations:
    external-dns.alpha.kubernetes.io/hostname: immich.${SECRET_DOMAIN}
    io.cilium/lb-ipam-ips: 10.10.40.91
spec:
  type: LoadBalancer
  ports:
    - name: immich
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: immich
    role: primary
---
apiVersion: v1
kind: Service
metadata:
  name: immich-r
spec:
  type: ClusterIP
  ports:
    - name: immich
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres17
    cnpg.io/podRole: instance
---
apiVersion: v1
kind: Service
metadata:
  name: immich-ro
spec:
  type: ClusterIP
  ports:
    - name: immich
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: immich
    role: replica
---
apiVersion: v1
kind: Service
metadata:
  name: immich-rw
spec:
  type: ClusterIP
  ports:
    - name: immich
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: immich
    role: primary
  sessionAffinity: None
