apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  TIMEZONE: ENC[AES256_GCM,data:7Rq7Ew2TcsBlEX+os8HnOw==,iv:EdaSs9BvYgYjWJ8sKTgFED0AMm/o2W9zFIA56gxEfr4=,tag:7aiSAm0jVPlMrXXyxbP4BQ==,type:str]
  SECRET_DOMAIN: ENC[AES256_GCM,data:gybhqmIhU2s=,iv:q0kvtW69l3MkqKiwvlMKoytMNsH29xQdFWXhU5mYau8=,tag:iBg1nvZTGS/J41b6W7PJQQ==,type:str]
  SECRET_GAMING_DOMAIN: ENC[AES256_GCM,data:lp1rR85VOcNw3FSBEg==,iv:Kv0GcndOw0JEXm6XTVpEbBNpY3pKuKiM/4cL9HCC32Q=,tag:EbZUODYDXDpRu88K/ij21A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZjNTeXdDckRXU0thMFdv
        ZU5nM1RWbVoyOCs0YURqR0R5cml0d0FrRFhNCmVwUHhPdHRtTXRXRlJQNXBYa3Bj
        RnZLajFMMU44TTNXSXR3TlYrR1RjU0kKLS0tIE8wcnhYRzNGdmFoMHlIZkhkNmEx
        N2xYbEV4WWtrUVo0eEdMWEF2VkJic0kKmQFPnmY630/+cg6w0gUdGQiDHRUAS+KE
        eCjTaHXwirjSHrH3x9SDTqG0Ob1xWMLV7BkGIm/akVLkRjA8chPURw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age16la8m5zvpastlq7jzmv5agmfkghq4ckw28jy8lacqqyxmw2c8y3s9cpunf
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-19T01:39:24Z"
  mac: ENC[AES256_GCM,data:HIfs67TdfxZZd8AQx2Qq6PYStU26dhf4Olkx2Jkz9W0WRDj3GJALGw7XAmvji5wLnrACO6vdywVPYMgqbMUii2+zXCPtgdHZ9DFid0sAhkk8mabYhR3yb9ymyRA9oh9yBijN9mvfYs25ryXVprRG3qoNb+YOZMYvnbbnMedj1nA=,iv:/aJeqGQ4tbWkIrbcoR1W7UQp73YqGbE7MkT6YzwuBZ4=,tag:qjizYTG9vwSDEBUCDemkjQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
