apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  TIMEZONE: ENC[AES256_GCM,data:7Rq7Ew2TcsBlEX+os8HnOw==,iv:EdaSs9BvYgYjWJ8sKTgFED0AMm/o2W9zFIA56gxEfr4=,tag:7aiSAm0jVPlMrXXyxbP4BQ==,type:str]
  SECRET_DOMAIN: ENC[AES256_GCM,data:gybhqmIhU2s=,iv:q0kvtW69l3MkqKiwvlMKoytMNsH29xQdFWXhU5mYau8=,tag:iBg1nvZTGS/J41b6W7PJQQ==,type:str]
  NIGHTSCOUT_MONGODB_PASSWORD: ENC[AES256_GCM,data:uVO73xDPMu7wJGQWjlj8/XISxAs=,iv:MpUPcFSEHW8hgPvD27OLfJkM7ViKnI8B1xQo88Kk+Fs=,tag:cUjqPnTMvTmZb1GNe09m4g==,type:str]
  NIGHTSCOUT_MONGODB_ROOT_PASSWORD: ENC[AES256_GCM,data:/5hz4o7MUjhhZ9sTi3wCxucrc2c=,iv:W06r29msL6zyjmSZbPvkUeYUbE9LxKfl4LWjs1QeY/A=,tag:jQkJ52ss/hzZdNH4r4mjKQ==,type:str]
  SECRET_NFS_SERVER: ENC[AES256_GCM,data:drFixPtjOLfyHg==,iv:M0I1ou8Bl/wFzUqIOB33vlmTErz5sCMYx2EJWut+3K4=,tag:1UhceV04GWoziwRreqtBCg==,type:str]
  SECRET_UNIFI_IP: ENC[AES256_GCM,data:r/R10R9CytS49jI=,iv:B22FvUpHxtIp4iGwOSlCRZ8FjTYGgZgAdD/jdgl+gfo=,tag:21Q9tL6SnNnrNzXJbjlDcA==,type:str]
  SECRET_WINGS_IP1: ENC[AES256_GCM,data:63vNvZvjMBpi3Vc=,iv:/G4/Lg+ByNWpxnAOZt08le9YXSyCg0C2M1ui6PqdLXM=,tag:gqI1cy0VcmPBWpaDQusxpA==,type:str]
  SECRET_WINGS_IP2: ENC[AES256_GCM,data:a9+5lgxQOfeFKfo=,iv:WK5ltypmGdnUKk0YGhJdJMghdOBkfyHXsdTGtVu+lak=,tag:8b7U+sjb2OODhl3X0UcOCA==,type:str]
  SECRET_WINGS_IP3: ENC[AES256_GCM,data:3SXAAAoLL/o5uuc=,iv:ggZaB2PPAomqpzyOpkKGeFN2qh0mc3FAkroiPZ++l6w=,tag:nPr+l45rctUKbww5VgFmAA==,type:str]
  SECRET_HOST_IP: ENC[AES256_GCM,data:th6LQ2OcfAyAZYk=,iv:wYSHu/Og4UsK/LMwsur3LvuOkh9P7dqiT1sU2FfMuno=,tag:OfnmVbWM1pQzF1lvLU6OeA==,type:str]
sops:
  age:
    - recipient: age16la8m5zvpastlq7jzmv5agmfkghq4ckw28jy8lacqqyxmw2c8y3s9cpunf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZjNTeXdDckRXU0thMFdv
        ZU5nM1RWbVoyOCs0YURqR0R5cml0d0FrRFhNCmVwUHhPdHRtTXRXRlJQNXBYa3Bj
        RnZLajFMMU44TTNXSXR3TlYrR1RjU0kKLS0tIE8wcnhYRzNGdmFoMHlIZkhkNmEx
        N2xYbEV4WWtrUVo0eEdMWEF2VkJic0kKmQFPnmY630/+cg6w0gUdGQiDHRUAS+KE
        eCjTaHXwirjSHrH3x9SDTqG0Ob1xWMLV7BkGIm/akVLkRjA8chPURw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-12T00:33:17Z"
  mac: ENC[AES256_GCM,data:YXClMbkBRky85HEKm/6oEHr57SC0DZuz38Yd5dlQkGg0YSjDPR7GM/cU7+DOu8arnzkYNQOKb+Bt7+76SQVB9lCB5mmm5Yaxovx40d4WQM979n75XYMuT+Y51im2mdPuuxOcu6SnX28g7l1V+JK0mdVu8xUihilgEjwz/QR2NbU=,iv:4BY8ElUIos7gEES/UQ1XMh70mne0a1N/iuFvFwyZ4dQ=,tag:4LOrbk8cozgX48O9189uTg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
