---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sparkyfitness
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sparkyfitness-secret
    template:
      engineVersion: v2
      data:
        # Security Configuration
        SPARKY_FITNESS_API_ENCRYPTION_KEY: "{{ .API_ENCRYPTION_KEY }}"
        JWT_SECRET: "{{ .JWT_SECRET }}"

        # Application Configuration
        SPARKY_FITNESS_FRONTEND_URL: "https://fitness.${SECRET_DOMAIN}"
        SPARKY_FITNESS_SERVER_HOST: "localhost"
        SPARKY_FITNESS_SERVER_PORT: "3010"
        SPARKY_FITNESS_LOG_LEVEL: "INFO"
        SPARKY_FITNESS_DISABLE_SIGNUP: "{{ .DISABLE_SIGNUP }}"
        # SPARKY_FITNESS_ADMIN_EMAIL: "{{ .ADMIN_EMAIL }}"
        SPARKY_FITNESS_FORCE_EMAIL_LOGIN: "true"

        # Environment Configuration
        NODE_ENV: "production"

        # Database configuration
        SPARKY_FITNESS_DB_USER: &dbuser "{{ .SPARKY_POSTGRES_USER }}"
        SPARKY_FITNESS_DB_PASSWORD: &dbpass "{{ .SPARKY_POSTGRES_PASSWORD }}"
        SPARKY_FITNESS_DB_HOST: &dbhost postgres17-rw.database.svc.cluster.local
        SPARKY_FITNESS_DB_NAME: &dbname sparkyfitness

        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: sparkyfitness
